version: "3.5"

networks:
  web:
    external: true

services:
  syncserver:
    build:
      args:
        ENABLE_HETZNER_REPO: $ENABLE_HETZNER_REPO
        APT_PROXY: $APT_PROXY
      network: apt-cacher-ng
    env_file:
      - secrets.env
    networks:
      default:
      web:
        aliases:
          firefox-syncserver
    restart: unless-stopped
  db:
    env_file:
      - secrets_db.env
    restart: unless-stopped
