version: "3.4"

services:
  bitwarden:
    build:
      context: bitwarden_rs
    env_file:
      - secrets.env
    environment:
      WEBSOCKET_ENABLED: "true"
    ports:
      - 127.0.0.1:5001:80
      - 127.0.0.1:3012:3012
    volumes:
      - ./data:/data
