version: "3.5"

services:
  nextcloud:
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "2"
  nginx:
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "2"
  cron:
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "2"
  db:
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "2"

