version: "3.5"

networks:
  ipv6-nat:
    external: true

services:
  bitcoind:
    build:
      args:
        ENABLE_HETZNER_REPO: $ENABLE_HETZNER_REPO
        APT_PROXY: $APT_PROXY
      network: apt-cacher-ng
    volumes:
      - /mnt/bitcoind-data:/data
    networks:
      ipv6-nat:
        ipv4_address: 172.18.50.1
        ipv6_address: fcdd:1::50:1
