version: "3.5"

networks:
  web:
    external: true

services:
  apt-cacher-ng:
    build:
      args:
        ENABLE_HETZNER_REPO: $ENABLE_HETZNER_REPO
        APT_PROXY: $APT_PROXY
      network: apt-cacher-ng
    restart: unless-stopped
    networks:
      - web
