<?php
$CONFIG = array (
  'instanceid' => $_SERVER['NEXTCLOUD_INSTANCE_ID'],
  'passwordsalt' => $_SERVER['NEXTCLOUD_PASSWORD_SALT'],
  'secret' => $_SERVER['NEXTCLOUD_SECRET'],
  'trusted_domains' => explode(',', $_SERVER['NEXTCLOUD_TRUSTED_DOMAINS']),
  'datadirectory' => '/srv/data',
  'overwrite.cli.url' => $_SERVER['NEXTCLOUD_OVERWRITE_CLI_URL'],
  'dbtype' => 'pgsql',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => $_SERVER['NEXTCLOUD_DB_PASSWORD'],
  'logtimezone' => 'UTC',
  'installed' => true,
  'default_language' => 'de',
  'mail_domain' => $_SERVER['NEXTCLOUD_MAIL_DOMAIN'],
  'mail_from_address' => $_SERVER['NEXTCLOUD_MAIL_FROM_ADDRESS'],
  'mail_smtpmode' => $_SERVER['NEXTCLOUD_MAIL_SMTPMODE'],
  'mail_smtphost' => $_SERVER['NEXTCLOUD_MAIL_SMTPHOST'],
  'mail_smtpport' => intval($_SERVER['NEXTCLOUD_MAIL_SMTPPORT']),
  'mail_smtpsecure' => $_SERVER['NEXTCLOUD_MAIL_SMTPSECURE'],
  'mail_smtpauth' => strtolower($_SERVER['NEXTCLOUD_MAIL_SMTPAUTH']) === 'true',
  'mail_smtpauthtype' => $_SERVER['NEXTCLOUD_MAIL_SMTPAUTHTYPE'],
  'mail_smtpname' => $_SERVER['NEXTCLOUD_MAIL_SMTPNAME'],
  'mail_smtppassword' => $_SERVER['NEXTCLOUD_MAIL_SMTPPASSWORD'],
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'theme' => '',
  'upgrade.disable-web' => true,
  'auth.bruteforce.protection.enabled' => false,
);
