version: "3.5"

volumes:
  config:

services:
  syncthing:
    build: .
    read_only: true
    ports:
      - 127.0.0.1:8384:8384
      - 22000
      - 21027/udp
    volumes:
      - config:/var/lib/syncthing/config
