version: "3.6"

services:
  influxdb:
    build: .
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - /mnt/docker-volumes/influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /run
