version: "3.6"

services:
  influxdb:
    build: .
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    read_only: true
    tmpfs:
      - /tmp
      - /run
