version: "3.6"

networks:
  web:
    external: true

services:
  influxdb:
    restart: unless-stopped
    networks:
      - web
    hostname: firefox-syncserver
    volumes:
      - /srv/docker/volumes/influxdb:/var/lib/influxdb
